export const SUPABASE_PUBLIC_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppamNncXhmbXJmd3poZWlmZWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDc0Njc0MjEsImV4cCI6MTk2MzA0MzQyMX0.fguVEDOvfmI5BmSJSCweh161j6A04mgUo2lzQmw3bjw";

export const SUPABASE_URL = "https://jijcgqxfmrfwzheifelg.supabase.co";
